import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./navbar/page";
import Foot from "./footer/page";
import UserProvider from "@/context/userContext/userContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <Nav />
          {children}
          <Foot />
        </UserProvider>
      </body>
    </html>
  );
}
